# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Badgerio"
license = "MIT"
licenselink = "https://github.com/BadgerIO/BadgerTheme/blob/master/badgerio/LICENSE.md"
description = ""
homepage = "https://github.com/BadgerIO/BadgerTheme"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
